<?php

/**
 * Implements hook_menu().
 */
function cqmu_menu() {
  $items['cqmu'] = array(
    'title' => '重庆医科大学',
    'page callback' => 'cqmu_page',
    'access arguments' => array('access content'),
    'type' => MENU_CALLBACK,
  );
  return $items;
}

/**
 * 回调函数
 * 第二行注释
 */
function cqmu_page() {
  // return "重医你好！";
  // return '欢迎了解 <a href="http://www.cqmu.edu.cn"> 重庆医科大学</a>';
  // render array
  // return array(
  //   "#markup" => "<b>重医你好！</b>"
  // );


  $nids = array();
  $query = new EntityFieldQuery();
  $query->entityCondition('entity_type', 'node')
    ->entityCondition('bundle', 'article')
    ->range(0, 5)
    ->addMetaData('account', user_load(1)); // Run the query as user 1.

  $result = $query->execute();

  dpm($result);

  if (isset($result['node'])) {
    $nids = array_keys($result['node']);
    dpm($nids);
  }



  $nodes = node_load_multiple($nids);
  // $nodes = node_load_multiple(array( 1, 3, 8));

  $html = "";
 

  $html = "<ol>";

  foreach ($nodes as $index => $node) {

    $html = $html . '<li><a href="node/' . $node->nid .'">' . $node->title .  '</a></li>';

  }
  // $html = $html . '<li><a href="node/3">第3篇文章</a></li>';
  // $html = $html . '<li><a href="node/8">第8篇文章</a></li>';
  $html = $html . "</ol>"; 

  // dpm($html, "html");

  return $html;

}


